//! Build script of the firmware: the linker script of the chip (memory/f401.x or f411.x, both
//! include memory/vdm.x) and the ID block (docs/rust/GLUE-DESIGN-STM.md §6.2) with the
//! workspace version and the board tag, laid out by vdm_stm_boot::id_block.
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};
use std::{env, fs};

use vdm_stm_boot::id_block::{self, ID_BLOCK_MAX};

fn feature(name: &str) -> bool {
    env::var_os(format!("CARGO_FEATURE_{}", name.to_uppercase())).is_some()
}

/// `version` of `[workspace.package]` in software_stm32_rust/Cargo.toml.
fn workspace_version(manifest: &str) -> Option<String> {
    let mut in_package = false;
    for line in manifest.lines() {
        let line = line.trim();
        if line.starts_with('[') {
            in_package = line == "[workspace.package]";
        } else if in_package {
            if let Some(value) = line.strip_prefix("version") {
                let value = value.trim_start().strip_prefix('=')?.trim();
                return Some(value.trim_matches('"').to_string());
            }
        }
    }
    None
}

fn main() {
    let dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));

    let chips: Vec<&str> = ["f401", "f411"]
        .into_iter()
        .filter(|c| feature(c))
        .collect();
    let boards: Vec<&str> = ["c1", "c2"].into_iter().filter(|b| feature(b)).collect();
    if chips.len() != 1 || boards.len() != 1 {
        // main.rs says it with compile_error!; nothing to generate without a chip and a board
        return;
    }

    // linker scripts: cortex-m-rt's link.x includes memory.x
    let memory = dir.join("memory");
    copy(
        &memory.join(format!("{}.x", chips[0])),
        &out.join("memory.x"),
    );
    copy(&memory.join("vdm.x"), &out.join("vdm.x"));
    println!("cargo:rustc-link-search={}", out.display());
    println!(
        "cargo:rustc-link-arg-bins=-Map={}",
        out.join("vdm-stm-fw.map").display()
    );

    // version and board of the image
    let ws_manifest = dir.join("..").join("Cargo.toml");
    let manifest = fs::read_to_string(&ws_manifest).expect("software_stm32_rust/Cargo.toml");
    let mut version = workspace_version(&manifest).expect("[workspace.package] version");
    let build = if feature("dev") {
        version.push_str("-dev");
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0)
            .to_string()
    } else {
        "1".to_string()
    };
    let tag = boards[0].to_uppercase();
    let mut block = [0u8; ID_BLOCK_MAX];
    let layout = id_block::write(version.as_bytes(), tag.as_bytes(), &mut block)
        .unwrap_or_else(|e| panic!("ID block for {version} / {tag}: {e:?}"));
    let bytes: Vec<String> = block[..layout.len]
        .iter()
        .map(|b| format!("{b:#04x}"))
        .collect();

    let generated = format!(
        "// generated by build.rs: the ID block of this image ({version}, VDM-HW:{tag})\n\
         /// The ID block at 0x08000200 (the linker script keeps `.vdm_id` there).\n\
         #[used]\n\
         #[link_section = \".vdm_id\"]\n\
         pub static VDM_ID: [u8; {len}] = [{bytes}];\n\
         pub const LAYOUT: vdm_stm_boot::id_block::IdLayout = vdm_stm_boot::id_block::IdLayout {{\n\
         \x20   version: {v}, version_len: {vl}, tag: {t}, tag_len: {tl},\n\
         \x20   pattern: {p}, reply: {r}, len: {len},\n\
         }};\n\
         /// The build field of `gvers`: \"1\" in release images, the build time with `dev`.\n\
         pub const BUILD: &[u8] = b\"{build}\";\n",
        len = layout.len,
        bytes = bytes.join(", "),
        v = layout.version,
        vl = layout.version_len,
        t = layout.tag,
        tl = layout.tag_len,
        p = layout.pattern,
        r = layout.reply,
    );
    fs::write(out.join("id_block.rs"), generated).expect("id_block.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=memory");
    println!("cargo:rerun-if-changed={}", ws_manifest.display());
}

fn copy(from: &Path, to: &Path) {
    fs::copy(from, to).unwrap_or_else(|e| panic!("{}: {e}", from.display()));
}
