//! VdMot Revamped STM32 firmware (docs/rust/GLUE-DESIGN-STM.md): the boot stage after every
//! reset (B1), then the application stage. Four images: features f401 | f411 x c1 | c2.
//!
//! `unsafe` lives only in main.rs, boot_hw.rs, isr.rs, noinit.rs and fault.rs (§1.1).
#![no_std]
#![no_main]

#[cfg(not(any(
    all(feature = "f401", not(feature = "f411")),
    all(feature = "f411", not(feature = "f401"))
)))]
compile_error!("select exactly one chip: feature f401 or f411");
#[cfg(not(any(
    all(feature = "c1", not(feature = "c2")),
    all(feature = "c2", not(feature = "c1"))
)))]
compile_error!("select exactly one board revision: feature c1 or c2");
#[cfg(all(feature = "boot-probe", feature = "app"))]
compile_error!("the boot probe links the boot stage alone: --no-default-features --features <chip>,<board>,boot-probe");

mod boot_hw;
mod fault;
mod noinit;

#[cfg(feature = "app")]
mod app;
#[cfg(feature = "app")]
mod clocks;

/// The ID block (generated by build.rs from the workspace version and the board).
#[allow(dead_code)]
mod id {
    include!(concat!(env!("OUT_DIR"), "/id_block.rs"));
}

use cortex_m_rt::entry;

#[entry]
fn main() -> ! {
    let token = boot_hw::run();
    #[cfg(feature = "app")]
    {
        app::run(token)
    }
    #[cfg(not(feature = "app"))]
    {
        boot_only(token)
    }
}

/// Without the application (boot probe): nothing after the window.
#[cfg(not(feature = "app"))]
fn boot_only(_token: vdm_stm_boot::BootToken) -> ! {
    fault::halt()
}

#[cfg(not(feature = "boot-probe"))]
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    fault::on_panic()
}

/// B3 (§5.1): the probe links the boot stage and the fault handlers with a panic handler that
/// calls a function that does not exist. Any panic path left in them fails the link with
/// "undefined symbol: vdm_boot_stage_has_a_panic_path".
#[cfg(feature = "boot-probe")]
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    extern "Rust" {
        fn vdm_boot_stage_has_a_panic_path() -> !;
    }
    // SAFETY: never runs; the symbol does not exist, so a reachable call fails the link
    unsafe { vdm_boot_stage_has_a_panic_path() }
}
