//! The dashboard (`software_esp32_revamped/web`, the one source of its files) as the table the
//! firmware passes to [`Web::new`](super::Web::new): generated by `build.rs` (feature
//! `dashboard`) with the gzip and ETag code of `gen_web_assets.py`.

use super::Asset;

/// Every file of the dashboard, in the order gen_web_assets.py collects them.
pub static DASHBOARD: &[Asset] = &include!(concat!(env!("OUT_DIR"), "/web_assets.rs"));
