//! The dashboard table of `web_server::assets` (feature `dashboard`, enabled by the firmware):
//! every file of `software_esp32_rust/web` gzip-compressed with the ETag of its gzip bytes by
//! the functions of `software_esp32_rust/tools/gen_web_assets.py` (level 9, mtime 0, no file
//! name, CRC32 ETags, the 160 KB budget), the bytes and ETags of the C++ 2.1.7 image. Needs
//! python3 at build time, as the ESP-IDF build does. Without the feature (host tests, mutation
//! runs) nothing is generated.
// a host build script: the stack rule of the glue (design 2.4) is for the device
#![allow(clippy::large_stack_frames)]

use std::env;
use std::path::PathBuf;
use std::process::Command;

/// Writes `<out>/web_assets.rs` (an array expression of `Asset`s) and the gzip files it
/// includes; arguments: the tools directory, the web directory, the output directory.
const GENERATE: &str = r#"
import json, os, sys, zlib
tools, web, out = sys.argv[1:4]
sys.path.insert(0, tools)
import gen_web_assets as g
files = g.collect(web)
if not files:
    raise SystemExit("gen_web_assets: no files in " + web)
rows, total = [], 0
for i, (url, path) in enumerate(files):
    ext = os.path.splitext(path)[1].lower()
    if ext not in g.CONTENT_TYPES:
        raise SystemExit("gen_web_assets: unsupported file type: " + path)
    with open(path, "rb") as f:
        gz = g.gzip_bytes(f.read())
    total += len(gz)
    name = os.path.join(out, "web_asset_%d.gz" % i)
    with open(name, "wb") as f:
        f.write(gz)
    etag = '"%08x"' % (zlib.crc32(gz) & 0xFFFFFFFF)
    rows.append((url, g.CONTENT_TYPES[ext], name, etag))
if total > g.MAX_TOTAL_GZ:
    raise SystemExit("gen_web_assets: embedded UI is %d B gzip, budget %d B" % (total, g.MAX_TOTAL_GZ))
q = lambda s: json.dumps(s, ensure_ascii=False)
with open(os.path.join(out, "web_assets.rs"), "w", encoding="utf-8", newline="\n") as f:
    f.write("// Generated by build.rs from software_esp32_rust/web. Do not edit.\n[\n")
    for url, ctype, name, etag in rows:
        f.write("    Asset { path: %s, content_type: %s, data: include_bytes!(%s), etag: %s },\n"
                % (q(url), q(ctype), q(name), q(etag)))
    f.write("]\n")
"#;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    if env::var_os("CARGO_FEATURE_DASHBOARD").is_none() {
        return;
    }
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let esp = manifest.join("..");
    let (tools, web) = (esp.join("tools"), esp.join("web"));
    println!("cargo:rerun-if-changed={}", web.display());
    println!(
        "cargo:rerun-if-changed={}",
        tools.join("gen_web_assets.py").display()
    );
    let out = env::var_os("OUT_DIR").expect("OUT_DIR");
    for python in ["python3", "python"] {
        // -B: no __pycache__ next to the tool
        let status = Command::new(python)
            .arg("-B")
            .arg("-c")
            .arg(GENERATE)
            .arg(&tools)
            .arg(&web)
            .arg(&out)
            .status();
        if let Ok(status) = status {
            assert!(
                status.success(),
                "dashboard: generating the assets of {} failed",
                web.display()
            );
            return;
        }
    }
    panic!("dashboard: python3 is needed to generate the assets");
}
