#!/usr/bin/env python3
"""Embed the dashboard (web/*) into the firmware as gzip byte arrays.

Generates src/generated/web_assets.h from every regular file in web/
(recursively, hidden files skipped). Each file is gzip-compressed
deterministically (level 9, mtime 0, no file name) so identical sources give
identical headers; the header is only rewritten when its content changes, so
unchanged assets never trigger a rebuild.

Runs automatically as a PlatformIO pre-build script (extra_scripts =
pre:tools/gen_web_assets.py) and standalone:

    python3 tools/gen_web_assets.py [PROJECT_DIR]

The header is included by exactly one translation unit (src/web_server.cpp).
"""
from __future__ import annotations

import gzip
import io
import os
import sys
import zlib

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".png": "image/png",
    ".txt": "text/plain; charset=utf-8",
}
# Budget for the embedded UI (compressed). The app image must stay < 1.1 MB.
MAX_TOTAL_GZ = 160 * 1024


def gzip_bytes(data: bytes) -> bytes:
    buf = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=buf, compresslevel=9, mtime=0) as gz:
        gz.write(data)
    return buf.getvalue()


def collect(web_dir: str) -> list[tuple[str, str]]:
    files = []
    for root, dirs, names in os.walk(web_dir):
        dirs[:] = sorted(d for d in dirs if not d.startswith("."))
        for name in sorted(names):
            if name.startswith("."):
                continue
            full = os.path.join(root, name)
            url = "/" + os.path.relpath(full, web_dir).replace(os.sep, "/")
            files.append((url, full))
    return files


def c_identifier(index: int) -> str:
    return f"kData{index}"


def render(files: list[tuple[str, str]]) -> tuple[str, int]:
    lines = [
        "// Generated by tools/gen_web_assets.py from web/. Do not edit.",
        "// Include from exactly one translation unit (src/web_server.cpp).",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "namespace web_assets {",
        "",
        "struct Asset {",
        "  const char* path;         // URL path, e.g. \"/index.html\"",
        "  const char* contentType;",
        "  const uint8_t* data;      // gzip (serve with Content-Encoding: gzip)",
        "  size_t length;",
        "  const char* etag;         // quoted CRC32 of the gzip bytes",
        "};",
        "",
    ]
    table = []
    total = 0
    for i, (url, path) in enumerate(files):
        ext = os.path.splitext(path)[1].lower()
        if ext not in CONTENT_TYPES:
            raise SystemExit(f"gen_web_assets: unsupported file type: {path}")
        with open(path, "rb") as f:
            gz = gzip_bytes(f.read())
        total += len(gz)
        etag = f'\\"{zlib.crc32(gz) & 0xFFFFFFFF:08x}\\"'
        ident = c_identifier(i)
        lines.append(f"// {url} ({len(gz)} bytes gzip)")
        lines.append(f"static const uint8_t {ident}[] = {{")
        for off in range(0, len(gz), 20):
            chunk = ", ".join(f"0x{b:02x}" for b in gz[off:off + 20])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")
        table.append(f'    {{"{url}", "{CONTENT_TYPES[ext]}", {ident}, sizeof({ident}), "{etag}"}},')
    lines.append("static const Asset kAssets[] = {")
    lines.extend(table)
    lines.append("};")
    lines.append(f"static const size_t kAssetCount = {len(files)};")
    lines.append("")
    lines.append("}  // namespace web_assets")
    lines.append("")
    return "\n".join(lines), total


def generate(project_dir: str) -> None:
    web_dir = os.path.join(project_dir, "web")
    out_path = os.path.join(project_dir, "src", "generated", "web_assets.h")
    files = collect(web_dir)
    if not files:
        raise SystemExit(f"gen_web_assets: no files in {web_dir}")
    text, total = render(files)
    if total > MAX_TOTAL_GZ:
        raise SystemExit(f"gen_web_assets: embedded UI is {total} B gzip, budget {MAX_TOTAL_GZ} B")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    old = None
    if os.path.exists(out_path):
        with open(out_path, "r", encoding="utf-8") as f:
            old = f.read()
    if old != text:
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"gen_web_assets: wrote {out_path} ({len(files)} files, {total} B gzip)")


try:
    Import("env")  # type: ignore[name-defined]  # noqa: F821 - provided by PlatformIO/SCons
    generate(env.subst("$PROJECT_DIR"))  # type: ignore[name-defined]  # noqa: F821
except NameError:
    if __name__ == "__main__":
        generate(os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else
                                 os.path.join(os.path.dirname(__file__), "..")))
